### ISSUE TITLE
terraform plan error

### ISSUE THREAD

**Issue by debragail** [lgallard/terraform-aws-secrets-manager#20] opened 2022-05-28 23:26 UTC
Error: Unsupported argument
│ 
│   on main.tf line 360, in module "secrets-manager-4":
│  360:   rotate_secrets = {
│ 
│ An argument named "rotate_secrets" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 375, in module "secrets-manager-4":
│  375:   tags = {
│ 
│ An argument named "tags" is not expected here.
╵

**Comment by mkarjun** [comment] 2022-11-25 07:16
Could you please specify more context : 

Error on main.tf line 360
1. - [ ]  Whether resource "aws_secretsmanager_secret_rotation" "rsm-sr" and var.rotate_secrets is specified and if yes : 

> - try changing the rotate_secrets variable to:
`variable "rotate_secrets" {
  description = "Map of secrets to keep and rotate in AWS Secrets Manager"
  type        = any
  default     = {}
}`

Error on main.tf line 375
1. - [ ]   Check whether the tags variable is given or not in the variable file.

> `variable "tags" {
  description = "Specifies a key-value map of user-defined tags that are attached to the secret."
  type        = any
  default     = {}
}`

Hope this helps, if not please specify more context on the issue.
As the issue is opened on May 29th, and if there are no further updates, we can close the issue.
cc: @debragail , @lgallard

**Comment by lgallard** [comment] 2022-11-25 11:54
@debragail I agree with @mkarjun, please provide more context: Terraform and AWS provider versions, snippet code, etc.

**Comment by lgallard** [comment] 2023-10-30 00:41
@debragail closing this as we didn't provide more context. Feel free to open another issue if your error persists.

**Closed by lgallard** 2023-10-30 00:41 UTC
